# Lista de Comida
comida = ['ARROZ', 'FEIJAO', 'CARNE', 'FRANGO', 'PEIXE', 'HAMBURGUER', 'PIZZA', 'MACARRAO', 'LASANHA', 'SUSHI', 'TACOS', 'TAPIOCA', 'COXINHA', 'BRIGADEIRO', 'CHURROS', 'SORVETE', 'PUDIM', 'BOLO', 'PAO', 'EMPADA', 'QUIBE', 'ESPARAGOS', 'STROGONOFF', 'CHURRASCO', 'SALADA']

# Lista de Animais
animais = ['CACHORRO', 'GATO', 'TIGRE', 'LEAO', 'ELEFANTE', 'GIRAFA', 'JACARE', 'LEOPARDO', 'PAPAGAIO', 'PATO', 'COELHO', 'GAVIAO', 'BALEIA', 'ORNITORRINCO', 'PANDA', 'VACA', 'GALINHA', 'PORCO', 'CAVALO', 'TARTARUGA', 'PEIXE', 'ARARA', 'COBRA', 'MACACO', 'LAGARTO']

# Lista de Objetos
objetos = ['CADEIRA', 'MESA', 'SOFA', 'COMPUTADOR', 'TELEFONE', 'CELULAR', 'TELEVISAO', 'GELADEIRA', 'FOGAO', 'MICROONDAS', 'VENTILADOR', 'CHUVEIRO', 'CAMA', 'TRAVESSEIRO', 'TOALHA', 'CANETA', 'LAPIS', 'BORRACHA', 'CADERNO', 'LIVRO', 'OCULOS', 'RELOGIO', 'BOLSA', 'CARTEIRA', 'CHAVE']

# Lista de Profissões
profissoes = ['MEDICO', 'PROFESSOR', 'ADVOGADO', 'ENGENHEIRO', 'ARQUITETO', 'COZINHEIRO', 'JORNALISTA', 'PROGRAMADOR', 'CONTADOR', 'DESIGNER', 'MOTORISTA', 'PILOTO', 'BOMBEIRO', 'POLICIAL', 'VENDEDOR', 'PSICOLOGO', 'FISIOTERAPEUTA', 'DENTISTA', 'ENFERMEIRO', 'MUSICO', 'ATLETA', 'ARTISTA', 'CINEASTA', 'ESCRITOR', 'CIENTISTA']

# Lista de Países
paises = ['BRASIL', 'ESTADOS UNIDOS', 'CANADA', 'MEXICO', 'ARGENTINA', 'ESPANHA', 'FRANCA', 'ITALIA', 'ALEMANHA', 'INGLATERRA', 'PORTUGAL', 'CHINA', 'JAPAO', 'INDIA', 'RUSSIA', 'AUSTRALIA', 'NOVA ZELANDIA', 'CHILE', 'COLOMBIA', 'VENEZUELA', 'EGITO', 'MARROCOS', 'AFRICA DO SUL', 'NIGERIA', 'GHANA']
